In [10]:
import numpy as np
import math

xl = float(input("Enter the lower value of x: "))
xu = float(input("Enter the higher value of x: "))
n = int(input("Number of iteration: "))

def f(x):
    return 5*x**3-5*x**2+6*x-2

x_l = np.zeros(n+1)
x_u = np.zeros(n+1)
x_r = np.zeros(n+1)
f_l = np.zeros(n+1)
f_u = np.zeros(n+1)
itr = np.zeros(n+1)

x_l[0] = xl
x_u[0] = xu

if f(xl)*f(xu)<0:
    for i in range(0,n+1):

        x_r[i] = (x_l[i]+x_u[i])/2

        
        if f(x_l[i])*f(x_r[i])<0:
            x_u[i+1] = x_r[i]
            x_l[i+1] = x_l[i]
        elif f(x_l[i])*f(x_r[i])>0:
            x_l[i+1] = x_r[i]
            x_u[i+1] = x_u[i]
        elif f(x_l[i])*f(x_r[i])==0:
            print("the answer is: ",x_r[i])
        
else:
    print("wrong initial value")
    
print(x_l)
print(x_u)
print(x_r)

Enter the lower value of x: 1
Enter the higher value of x: 2
Number of iteration: 9
wrong initial value
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
