In [4]:
## complex method
import numpy as np
import pandas as pd
import openpyxl
import matplotlib.pyplot as plt

# taking data from xls files
#data = pd.read_excel(r"C:/Users/tanji/Desktop/new.xlsx",sheet_name='Sheet1')

wb = openpyxl.load_workbook(r"C:/Users/tanji/Desktop/new.xlsx")


# Storing xlsx data in array
x = np.zeros(6)
print(x)
for i in range(2,8):
    r = "A"+str(i)
    x[i-2] = wb['Sheet1'][r].value #to excess data------ data = wb['sheet name']['number of cell number']
print(x)

y = np.zeros(6)
print(y)
for i in range(2,8):
    r = "B"+str(i)
    y[i-2] = wb['Sheet1'][r].value
print(y)
print()

[0. 0. 0. 0. 0. 0.]
[0. 1. 2. 3. 4. 5.]
[0. 0. 0. 0. 0. 0.]
[ 2.1  7.7 13.6 27.2 40.9 61.1]


In [6]:
# easy method
import numpy as np
import openpyxl

wb = openpyxl.load_workbook(r"C:/Users/tanji/Desktop/new.xlsx")

# Storing xlsx data in array
x = np.zeros(6)
y = np.zeros(6)

for i in range(2,8):
    x[i-2] = wb['Sheet1'].cell(i,1).value
    y[i-2] = wb['Sheet1'].cell(i,2).value
print(x)    
print(y)


[0. 1. 2. 3. 4. 5.]
[ 2.1  7.7 13.6 27.2 40.9 61.1]


In [ ]:
n = wb['Sheet'+str(a)].max_row - 1# to find number of data