In [46]:
import numpy as np

n = int(input("Enter the number of variable:"))

f = np.zeros((n,n+1))
print(f)
print("Enter the value of coefficient:")
for i in range(0,n):
    for j in range(0,n+1):
        f[i,j] = float(input("f["+str(i)+","+str(j)+"]:"))

print("The matrix version of the three function:\n",f)        

Enter the number of variable:4
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Enter the value of coefficient:
f[0,0]:12
f[0,1]:13
f[0,2]:23
f[0,3]:34
f[0,4]:45
f[1,0]:56
f[1,1]:67
f[1,2]:78
f[1,3]:89
f[1,4]:78
f[2,0]:67
f[2,1]:56
f[2,2]:67
f[2,3]:56
f[2,4]:78
f[3,0]:45
f[3,1]:65
f[3,2]:73
f[3,3]:83
f[3,4]:67
The matrix version of the three function:
 [[12. 13. 23. 34. 45.]
 [56. 67. 78. 89. 78.]
 [67. 56. 67. 56. 78.]
 [45. 65. 73. 83. 67.]]


In [33]:
#Gauss elimination section
def gauss_elimination(a):
    for j in range(0,n+1):
        for i in range(j,n):
            if a[i,j] != 0.0:
                a[i+1:,j] = ((a[i,j]/a[j,j])*a[i+1,j])-a[i+1:,j]
    return a;
result = gauss_elimination(f)
print(result)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [37]:
#Gauss elimination section
def gauss_elition(a):
    for j in range(0,n+1):
        for i in range(j,n):
            a[i,j] = a[i,j]/a[i,i]
    return a;
result = gauss_elition(f)
print(result)
print(result)

[[1.         2.         3.         4.        ]
 [0.         1.         7.         8.        ]
 [0.57142857 1.14285714 1.         6.        ]]
[[1.         2.         3.         4.        ]
 [0.         1.         7.         8.        ]
 [0.57142857 1.14285714 1.         6.        ]]


In [70]:
z = np.copy(f)
def gauss_jordan(a):
    a[0,:] = a[0,:]/a[0,0] 
    a[1,:] = (a[0,:]*a[1,0])- a[1,:]
    a[2,:] = (a[0,:]*a[2,0])- a[2,:]

    a[2,:] = ((a[1,:]/a[1,1])*a[2,1])- a[2,:]
    a[0,:] = a[0,:]-((a[1,:]/a[1,1])*a[0,1])

    a[0,:] = a[0,:]-((a[2,:]/a[2,2])*a[0,2])
    a[1,:] = a[1,:]-((a[2,:]/a[2,2])*a[1,2])

    a[1,:] = a[1,:]/a[1,1]
    a[2,:] = a[2,:]/a[2,2]

    x1 = a[0,3]
    x2 = a[1,3]
    x3 = a[2,3]
    return x1,x2,x3

print(gauss_jordan(z))


(3.0, -2.5, 7.000000000000002)


In [40]:
def gauss(a):
    a[0,:] = a[0,:]/a[0,0] 
    a[1,:] = (a[0,:]*a[1,0])- a[1,:]
    a[2,:] = (a[0,:]*a[2,0])- a[2,:]

    a[2,:] = ((a[1,:]/a[1,1])*a[2,1])- a[2,:]
    return a
print(gauss(f))


[[ 1.          2.          3.          4.        ]
 [ 0.         -1.         -7.         -8.        ]
 [ 0.          0.         -0.71428571  3.71428571]]


In [54]:
def gauss_elimination(a):
    for j in range(0,n-1):
        for i in range(j,n-1):
            if a[j,j] != 0.0: 
                a[j,:] = a[j,:]/a[j,j] # different for nested loop this should loop for only one
                a[i+1,:] = (a[j,:]*a[i+1,j])-a[i+1,:]#j0,1
    return a
print(gauss_elimination(f))

[[nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]
 [nan nan nan nan nan]]


In [52]:
def elimination(a):
    for i in range(0,n):
        for j in range(0,n):
            limit = a[i,j]/a[i,i]
            for k in range(i+1,n):
                a[k,i] = a[k,i]*limit-a[k,i]
                print(a[k,i])
                
    return a
print(elimination(f))
                
                

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
[[         nan          nan          nan          nan   3.75      ]
 [         nan          nan          nan          nan -20.84210526]
 [         nan          nan          nan          nan   3.8151911 ]
 [         nan          nan          nan          nan -51.19871795]]
