### User input section

In [23]:
import numpy as np

n = int(input("Enter the number of variable:"))

f = np.zeros((n,n+1))
print(f)
print("Enter the value of coefficient:")
for i in range(0,n):
    for j in range(0,n+1):
        f[i,j] = float(input("f["+str(i)+","+str(j)+"]:"))

print("The matrix version of the three function:\n",f)        

Enter the number of variable:4
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Enter the value of coefficient:
f[0,0]:1
f[0,1]:2
f[0,2]:-1
f[0,3]:1
f[0,4]:6
f[1,0]:-1
f[1,1]:1
f[1,2]:2
f[1,3]:-1
f[1,4]:3
f[2,0]:2
f[2,1]:-1
f[2,2]:2
f[2,3]:2
f[2,4]:14
f[3,0]:1
f[3,1]:1
f[3,2]:-1
f[3,3]:2
f[3,4]:8
The matrix version of the three function:
 [[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]]


### Elimination section

In [24]:
def gauss_jordan(a):
    for j in range(0,n):
        if a[j,j] != 0.0: 
            a[j,:] = a[j,:]/a[j,j]
        for i in range(0,n):
            if i != j:
                if i>j: 
                    a[i,:] = (a[j,:]*a[i,j])-a[i,:]
                else:
                    a[i,:] = a[i,:]-(a[j,:]*a[i,j])
    return a
print(gauss_jordan(f))

for i in range(0,n):
    print('\nx'+str(i)+' = ',f[i,n])


[[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [-0.  0.  1.  0.  3.]
 [-0. -0. -0.  1.  4.]]

x0 =  1.0

x1 =  2.0

x2 =  3.0000000000000004

x3 =  4.0
