### User input phase

In [42]:
import numpy as np

n = int(input("Enter the number of variable:"))

f = np.zeros((n,n+1))
print(f)
print("Enter the value of coefficient:")
for i in range(0,n):
    for j in range(0,n+1):
        f[i,j] = float(input("f["+str(i)+","+str(j)+"]:"))

print("The matrix version of the three function:\n",f)        

Enter the number of variable:4
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Enter the value of coefficient:
f[0,0]:1
f[0,1]:2
f[0,2]:-1
f[0,3]:1
f[0,4]:6
f[1,0]:-1
f[1,1]:1
f[1,2]:2
f[1,3]:-1
f[1,4]:3
f[2,0]:2
f[2,1]:-1
f[2,2]:2
f[2,3]:2
f[2,4]:14
f[3,0]:1
f[3,1]:1
f[3,2]:-1
f[3,3]:2
f[3,4]:8
The matrix version of the three function:
 [[ 1.  2. -1.  1.  6.]
 [-1.  1.  2. -1.  3.]
 [ 2. -1.  2.  2. 14.]
 [ 1.  1. -1.  2.  8.]]


### Elimination phase

In [49]:
def gauss_elimination(a):
    for j in range(0,n):
        for i in range(j,n-1):
            if a[j,j] != 0.0: 
                a[j,:] = a[j,:]/a[j,j]
                a[i+1,:] = (a[j,:]*a[i+1,j])-a[i+1,:]
    return a
print(gauss_elimination(f))

[[ 1.          2.         -1.          1.          6.        ]
 [-0.          1.          0.33333333 -0.          3.        ]
 [-0.          0.          1.         -0.          3.        ]
 [ 0.          0.          0.          1.          4.        ]]


### back substituition

In [50]:
for i in range(n-1,-1,-1):
    x[i] = f[i,n]
    for j in range(i+1,n):
        x[i] = x[i]-f[i,j]*x[j]
print(x)

# printing the results
for i in range(0,n):
    print('\nx'+str(i)+'= ',x[i])

[1. 2. 3. 4.]

x0=  1.0

x1=  2.0

x2=  3.0000000000000004

x3=  4.0
