In [17]:
import numpy as np
import openpyxl
import math

n = int(input("Numnber of variables: "))

f = np.zeros((n,n+1))

for i in range(0,n):
    for j in range(0,n+1):
        f[i,j] = float(input('f['+str(i)+','+str(j)+']: '))

print("\nThe ultimate matrix representation is:\n",f)

Numnber of variables: 3
f[0,0]: 2
f[0,1]: 4
f[0,2]: 5
f[0,3]: 6
f[1,0]: 7
f[1,1]: 5
f[1,2]: 3
f[1,3]: 4
f[2,0]: 6
f[2,1]: 5
f[2,2]: 7
f[2,3]: 8

The ultimate matrix representation is:
 [[2. 4. 5. 6.]
 [7. 5. 3. 4.]
 [6. 5. 7. 8.]]


In [29]:
b = np.copy(f)
print(b)

def U(a):
    for j in range(0,n):
        for i in range(j,n-1):
            if a[j,j] != 0.0: 
                a[j,:] = (a[j,:]/a[j,j])
                a[i+1,:] = ((a[j,:]/a[j,j])*a[i+1,j])-a[i+1,:]
    return a
print(U(b))

[[2. 4. 5. 6.]
 [7. 5. 3. 4.]
 [6. 5. 7. 8.]]
[[1.         2.         2.5        3.        ]
 [0.         1.         1.61111111 1.88888889]
 [0.         0.         3.27777778 3.22222222]]
