In [15]:
import numpy as np
import math

l = float(input("Enter th5e lower range of x: " ))
u = float(input("Enter the higher range of x: " ))
h = float(input("Enter the step size: "))

def f(x,y):
    return x+y
n = int(((u-l)/h)+1)
x = np.zeros(n)
y = np.zeros(n)
print(x)
print(y)

print("enter the intial condition:\n")
x[0] = input("x[0]: ")
y[0] = input("y[0]: ")

def heuns(a):
    for i in range(1,n):
        k1 = a*f(x[i-1],y[i-1])
        k2 = a*f(x[i-1]+a,y[i-1]+k1)
        k = .5*(k1+k2)
        y[i] = y[i-1]+k
        x[i] = x[i-1]+a
    print(x)
    print(y)

def midpoint(a):
    for i in range(1,n):
        k1 = a*f(x[i-1],y[i-1])
        k2 = a*f(x[i-1]+a,y[i-1]+k1)
        y[i] = y[i-1]+k2
        x[i] = x[i-1]+a
    print(x)
    print(y)

def ralston(a):
    for i in range(1,n):
        k1 = a*f(x[i-1],y[i-1])
        k2 = a*f(x[i-1]+a,y[i-1]+k1)
        k = (k1(1/3)+k2(2/3))
        y[i] = y[i-1]+k
        x[i] = x[i-1]+a
    print(x)
    print(y)

def eulers(a):
    for i in range(1,n):
        y[i] = y[i-1]+f(x[i-1],y[i-1])*a
        x[i] = x[i-1]+a
    print(x)
    print(y)

    
method = str(input("Enter the method(huens = h, midpoint = m, ralston = r): "))

if method == "h":
    print(heuns(h))
elif method == "m":
    print(midpoint(h))
elif method == "r":
    print(ralston(h))
if 


Enter th5e lower range of x: 0
Enter the higher range of x: .2
Enter the step size: .1
[0. 0. 0.]
[0. 0. 0.]
enter the intial condition:

x[0]: 0
y[0]: 1
Enter the method: h
[0.  0.1 0.2]
[1.      1.11    1.24205]
None
